# -*- coding: utf-8 -*-
"""crnn_baseline_improved.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vkilco6kZ1fnB7AhnSV5Rp8cB6HhJESq

# Distorted Visual Sequence Recognition using Deep Learning

## Problem
Given a dataset of grayscale images containing 6-character alphanumeric
sequences affected by heavy distortions, build a model that correctly
predicts the character sequence from each image.

**Distortion types present in the dataset:**
- Large black elliptical blob occluding parts of characters
- Background noise and visual artifacts
- Irregular character spacing and alignment
- Shape deformation and blur

**Evaluation metric:** Character Error Rate (CER) based on Levenshtein
distance — lower is better. A CER of 0.0 means every character is
predicted perfectly.

**Dataset:** 20,000 training images, 5,000 test images.  
**Vocabulary:** 38 characters — digits (0-9), uppercase letters
(excluding I, L, O), lowercase 'a' and 'r', and symbols (+, -, .)
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

!pip install textdistance -q

from pathlib import Path

TRAIN_IMG_DIR = Path("/content/drive/MyDrive/train_images")
TRAIN_CSV     = Path("/content/drive/MyDrive/train-labels.csv")
TEST_IMG_DIR  = Path("/content/drive/MyDrive/test_images")

import os
print(os.path.exists(TRAIN_IMG_DIR))  # must print True
print(os.path.exists(TRAIN_CSV))      # must print True
print(os.path.exists(TEST_IMG_DIR))   # must print True

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as tranforms
import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
from pathlib import Path
import textdistance
from sklearn.model_selection import train_test_split

# ─── TO DEFINE THE GPU DEVICE ───
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

import shutil, os

LOCAL_TRAIN = Path("/content/train_images")
LOCAL_TRAIN.mkdir(exist_ok=True)

files = list(TRAIN_IMG_DIR.glob("*"))
for i, f in enumerate(files):
    shutil.copy(f, LOCAL_TRAIN / f.name)
    if i % 1000 == 0:
        print(f"{i}/{len(files)} copied...")

LOCAL_TEST = Path("/content/test_images")
LOCAL_TEST.mkdir(exist_ok=True)

files = list(TEST_IMG_DIR.glob("*"))
for i, f in enumerate(files):
    shutil.copy(f, LOCAL_TEST / f.name)
    if i % 1000 == 0:
        print(f"{i}/{len(files)} copied...")

TRAIN_IMG_DIR = LOCAL_TRAIN
TEST_IMG_DIR  = LOCAL_TEST

"""## Dataset Analysis

Before building any model, we inspect the data to understand what
we are working with.

**Key observations:**
- All training labels are exactly 6 characters long (2 dirty rows removed)
- The vocabulary has 38 unique characters — notably, visually ambiguous
  letters (I, L, O) are excluded, likely intentional to reduce confusion
  with digits (1, 1, 0)
- The black blob varies in size and position across images — sometimes
  covering the left half, sometimes the center, sometimes spanning the
  full width
- Characters outside the blob region are relatively clean and readable
- The noise pattern is consistent — small scattered dots across the
  entire image background

**Critical insight for model design:** This is not a standard OCR problem.
The blob creates heavy partial occlusion that cannot be solved by
preprocessing alone — the model must learn to read characters from
partial evidence and use context from neighboring characters to resolve
ambiguity.
"""

CHARS = ['+', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7',
         '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J',
         'K', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W',
         'X', 'Y', 'Z', 'a', 'r']

BLANK = '-ctc-'
VOCAB = [BLANK] + CHARS
char2idx = {c: i for i, c in enumerate(VOCAB)}
idx2char = {i: c for c, i in char2idx.items()}

NUM_CLASSES = len(VOCAB)  # 39
SEQ_LEN = 6

print(f"Vocabulary size: {NUM_CLASSES}")

test_files = list(Path(TEST_IMG_DIR).glob("*.png"))
print(f"Total test images: {len(test_files)}")

# Check for duplicates
names = [f.name for f in test_files]
print(f"Unique names: {len(set(names))}")

#Pre-load datasets into RAM
class CaptchaDataset(Dataset):
    def __init__(self, df, img_dir):
        self.img_dir = Path(img_dir)
        original_len = len(df)
        self.df = df[df['text'].apply(lambda x: len(str(x)) == 6)].reset_index(drop=True)
        print(f"Dataset: {len(self.df)} valid samples ({original_len - len(self.df)} removed)")

        # Preload all images into RAM (CAPTCHAs are tiny, ~few hundred MB max)
        print("Preloading images into RAM...")
        self.images = []
        for idx in range(len(self.df)):
            img_name = self.df.iloc[idx]['image']
            img = cv2.imread(str(self.img_dir / img_name), cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, (128, 32))
            img = np.expand_dims(img, axis=0).astype(np.float32) / 255.0
            self.images.append(torch.tensor(img))
        print("Done preloading.")

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        label_str = str(self.df.iloc[idx]['text'])
        label_encoded = torch.tensor([char2idx[c] for c in label_str], dtype=torch.long)
        return self.images[idx], label_encoded, label_str

df = pd.read_csv(TRAIN_CSV)
train_df, val_df = train_test_split(df, test_size=0.1, random_state=42)

train_dataset = CaptchaDataset(train_df, TRAIN_IMG_DIR)
val_dataset   = CaptchaDataset(val_df,   TRAIN_IMG_DIR)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True,  num_workers=0, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=64, shuffle=False, num_workers=0, pin_memory=True)

imgs, labels, label_strs = next(iter(train_loader))
print(f"Batch shape: {imgs.shape}")
print(f"Sample: {label_strs[0]}")

"""## Baseline Architecture — Why CRNN?

### Why not a plain CNN classifier?
A fixed-length output (6 characters) means we could theoretically use
6 independent CNN classifiers — one per position. But this ignores
sequential context. When a character is partially occluded, neighboring
characters provide strong contextual cues. A sequential model can use
"the character after this blob looks like N, and the partial stroke
before it is consistent with D" — a plain classifier cannot.

### The CRNN architecture
**CNN (5 convolutional blocks):**  
Extracts visual features from the image column by column. Each block
applies Conv2d → BatchNorm → ReLU → MaxPool. The image (1×32×128) is
progressively compressed to (256×1×32), producing 32 feature vectors —
one per horizontal time step. Each time step roughly corresponds to a
vertical slice of the image.

**Bidirectional LSTM (2 layers, 256 hidden units):**  
Reads the 32 feature columns both left-to-right and right-to-left
simultaneously. Bidirectionality is important — the model can use
context from the right side of the sequence to resolve ambiguity on
the left, and vice versa. For occluded characters, this is critical.

**CTC Loss (Connectionist Temporal Classification):**  
Standard cross-entropy requires exact character-level alignment between
input positions and output labels. CTC does not — it learns the alignment
automatically by summing over all valid alignments during training. This
is essential when character positions vary due to distortion and irregular
spacing.

### Training observations
The model exhibited a characteristic CTC training pattern — a long plateau
(epochs 1-18, CER ~0.96) followed by a sudden breakthrough at epoch 19
(CER dropped to 0.87). This plateau occurs because CTC must simultaneously
learn feature extraction AND sequence alignment, creating a difficult
optimization landscape. Once the model finds a viable alignment strategy,
improvement is rapid. Final baseline CER: **0.0208**.
"""

class CRNN(nn.Module):
    def __init__(self, num_classes):
        super(CRNN, self).__init__()

        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d((2,1), (2,1)),

            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d((2,1), (2,1)),

            nn.Conv2d(256, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d((2,1), (2,1)),
        )

        self.rnn = nn.LSTM(256, 256, num_layers=2,
                           batch_first=True,
                           bidirectional=True,
                           dropout=0.3)

        self.fc = nn.Linear(512, num_classes)

    def forward(self, x):
        features = self.cnn(x)
        b, c, h, w = features.size()
        features = features.squeeze(2)
        features = features.permute(0, 2, 1)
        output, _ = self.rnn(features)
        output = self.fc(output)
        output = output.permute(1, 0, 2)
        return output

model = CRNN(num_classes=NUM_CLASSES)
model = model.to(device)
print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CTCLoss(blank=0, reduction='mean')
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=3
)

def encode_labels(label_strs):
    targets, target_lengths = [], []
    for s in label_strs:
        encoded = [char2idx[c] for c in s]
        targets.extend(encoded)
        target_lengths.append(len(s))
    return torch.tensor(targets, dtype=torch.long), \
           torch.tensor(target_lengths, dtype=torch.long)

def decode_predictions(outputs):
    _, max_indices = outputs.max(2)
    max_indices = max_indices.permute(1, 0).cpu().numpy()
    decoded = []
    for sequence in max_indices:
        chars = []
        prev = None
        for idx in sequence:
            if idx != prev and idx != 0:
                chars.append(idx2char[idx])
            prev = idx
        decoded.append("".join(chars))
    return decoded

def compute_cer(predictions, targets):
    total_dist = sum(textdistance.levenshtein(p, t) for p, t in zip(predictions, targets))
    total_len  = sum(len(t) for t in targets)
    return total_dist / total_len if total_len > 0 else 0

scaler = torch.cuda.amp.GradScaler()

def train_one_epoch(model, train_loader, optimizer, criterion, device):
    model.train()
    running_loss = 0.0

    for images, labels, label_strs in train_loader:
        images = images.to(device, non_blocking=True)
        targets, target_lengths = encode_labels(label_strs)
        targets = targets.to(device, non_blocking=True)
        target_lengths = target_lengths.to(device, non_blocking=True)

        optimizer.zero_grad()

        with torch.cuda.amp.autocast():  # ← mixed precision
            outputs = model(images)
            log_probs = outputs.log_softmax(2)
            input_lengths = torch.full((images.size(0),), outputs.size(0),
                                       dtype=torch.long, device=device)
            loss = criterion(log_probs, targets, input_lengths, target_lengths)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()

    return running_loss / len(train_loader)


def validate(model, loader, criterion, device):
    model.eval()
    total_loss = 0
    all_preds, all_targets = [], []

    with torch.no_grad():
        for imgs, labels, label_strs in loader:
            imgs = imgs.to(device, non_blocking=True)

            with torch.cuda.amp.autocast():  # ← mixed precision here too
                outputs = model(imgs)
                targets, target_lengths = encode_labels(label_strs)
                targets = targets.to(device, non_blocking=True)
                target_lengths = target_lengths.to(device, non_blocking=True)
                input_lengths = torch.full((imgs.size(0),), outputs.size(0),
                                           dtype=torch.long, device=device)
                log_probs = outputs.log_softmax(2)
                loss = criterion(log_probs, targets, input_lengths, target_lengths)

            total_loss += loss.item()
            all_preds.extend(decode_predictions(outputs))
            all_targets.extend(label_strs)

    cer = compute_cer(all_preds, all_targets)
    return total_loss / len(loader), cer, all_preds[:5], all_targets[:5]

NUM_EPOCHS = 30
best_cer = float('inf')
history = {"train_loss": [], "val_loss": [], "val_cer": []}

for epoch in range(NUM_EPOCHS):
    print(f"\nEpoch {epoch+1}/{NUM_EPOCHS}")
    print("-" * 40)

    train_loss = train_one_epoch(model, train_loader, optimizer, criterion, device)
    val_loss, val_cer, sample_preds, sample_targets = validate(model, val_loader, criterion, device)
    scheduler.step(val_loss)

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["val_cer"].append(val_cer)

    print(f"Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val CER: {val_cer:.4f}")
    print(f"Predictions: {sample_preds}")
    print(f"Targets:     {sample_targets}")

    if val_cer < best_cer:
        best_cer = val_cer
        torch.save(model.state_dict(), "/content/drive/MyDrive/best_model.pth")
        print(f"  ✓ Saved best model (CER: {best_cer:.4f})")

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

ax1.plot(history['train_loss'], label='Train Loss')
ax1.plot(history['val_loss'], label='Val Loss')
ax1.set_xlabel('Epoch')
ax1.set_ylabel('Loss')
ax1.set_title('Training & Validation Loss')
ax1.legend()

ax2.plot(history['val_cer'], label='Val CER', color='green')
ax2.set_xlabel('Epoch')
ax2.set_ylabel('CER')
ax2.set_title('Validation CER over Epochs')
ax2.legend()

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/training_curves.png", dpi=150)
plt.show()

"""## Error Analysis

The baseline achieved 85.85% full-sequence accuracy (1,717/2,000 correct).
Of the 283 incorrect sequences, we analyse which characters are being
confused and why.

| True Character | Confused As | Count | Visual Reason |
|---------------|-------------|-------|---------------|
| C | G | 17 | Both open round characters — blob occludes C's opening, making it appear closed like G |
| 6 | 8 | 17 | Both have closed loops — upper portion of 6 resembles 8 under noise |
| F | P | 11 | Both have vertical stroke + horizontal bars — lower bar of F occluded |
| 5 | 8 | 11 | Similar curve structure in upper half |
| Z | 2 | 9 | Similar diagonal stroke pattern |
| 3 | 9 | 8 | Upper curve similar, lower portion occluded by blob |

**Key insight:** The model's errors are not random — every top confused
pair shares a geometric similarity that becomes ambiguous specifically
under blob occlusion and noise. The model is genuinely reading the images.
It fails only when visual evidence is genuinely ambiguous.

**Hypothesis from this analysis:** The baseline BiLSTM treats all 32
time steps equally. But the blob dominates the center of every image —
those time steps contain almost no character information. If the model
could learn to downweight blob-dominated regions and upweight
character-rich regions at the image edges, it should resolve many of
these confusions. This motivates adding an **attention mechanism**.
"""

# Run on full validation set and collect errors
model.eval()
error_cases = []
char_errors = {}

with torch.no_grad():
    for imgs, labels, label_strs in val_loader:
        imgs = imgs.to(device)
        with torch.amp.autocast('cuda'):
            outputs = model(imgs)
        preds = decode_predictions(outputs)

        for pred, target in zip(preds, label_strs):
            if pred != target:
                error_cases.append((pred, target))
            # Per-character analysis
            for i, (p, t) in enumerate(zip(pred, target)):
                if p != t:
                    key = t  # true character
                    if key not in char_errors:
                        char_errors[key] = []
                    char_errors[key].append(p)  # what it predicted instead

print(f"Total errors: {len(error_cases)} / {len(val_dataset)}")
print(f"Accuracy: {1 - len(error_cases)/len(val_dataset):.4f}")
print(f"\nTop confused characters:")
for char, mistakes in sorted(char_errors.items(), key=lambda x: len(x[1]), reverse=True)[:10]:
    print(f"  '{char}' confused as: {dict(pd.Series(mistakes).value_counts().head(3).items())}")

# Visualize worst confused pairs
import matplotlib.pyplot as plt
import random

# Find error cases for C→G confusion (worst one)
target_char = 'C'
confused_as = 'G'

confused_samples = []
model.eval()

with torch.no_grad():
    for imgs, labels, label_strs in val_loader:
        imgs_gpu = imgs.to(device)
        with torch.amp.autocast('cuda'):
            outputs = model(imgs_gpu)
        preds = decode_predictions(outputs)

        for img, pred, target in zip(imgs, preds, label_strs):
            if len(pred) == len(target):
                for i, (p, t) in enumerate(zip(pred, target)):
                    if t == target_char and p == confused_as:
                        confused_samples.append((img, pred, target))
            if len(confused_samples) >= 8:
                break
        if len(confused_samples) >= 8:
            break

# Plot them
fig, axes = plt.subplots(2, 4, figsize=(14, 4))
fig.suptitle(f"'{target_char}' confused as '{confused_as}' — visually similar under occlusion",
             fontsize=12)
for i, ax in enumerate(axes.flat):
    if i < len(confused_samples):
        img, pred, target = confused_samples[i]
        ax.imshow(img.squeeze().numpy(), cmap='gray')
        ax.set_title(f"True: {target}\nPred: {pred}", fontsize=9, color='red')
    ax.axis('off')
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/confusion_visualization.png", dpi=150)
plt.show()

"""## Hypothesis — Why Attention?

The error analysis revealed a clear pattern: the model's mistakes
are concentrated in characters occluded by the black blob.
The baseline BiLSTM treats all 32 time steps equally — it has no
mechanism to say "this region of the image matters more than that one."

**Hypothesis:** Adding an attention mechanism on top of the BiLSTM
will allow the model to upweight time steps corresponding to visible
character regions and downweight blob-dominated regions, reducing
confusion in occluded areas.

**Implementation:** A lightweight additive attention layer with a
residual connection. The residual is critical — it ensures stable
gradient flow during early training when attention weights are random.
"""

class Attention(nn.Module):
    def __init__(self, hidden_size):
        super(Attention, self).__init__()
        self.attention = nn.Linear(hidden_size, 1)

    def forward(self, lstm_output):
        # lstm_output: (batch, time_steps, hidden_size)
        weights = self.attention(lstm_output)        # (batch, time_steps, 1)
        weights = torch.softmax(weights, dim=1)      # normalize across time steps
        context = lstm_output * weights              # weighted hidden states
        return context, weights


class AttentionCRNN(nn.Module):
    def __init__(self, num_classes):
        super(AttentionCRNN, self).__init__()

        # Same CNN as before
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d((2,1), (2,1)),

            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d((2,1), (2,1)),

            nn.Conv2d(256, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d((2,1), (2,1)),
        )

        # Same BiLSTM
        self.rnn = nn.LSTM(256, 256, num_layers=2,
                           batch_first=True,
                           bidirectional=True,
                           dropout=0.3)

        # NEW — attention layer
        self.attention = Attention(512)  # 512 = 256*2 bidirectional

        # NEW — slightly wider FC to compensate for attention compression
        self.fc = nn.Linear(512, num_classes)

    def forward(self, x):
    # CNN
      features = self.cnn(x)
      b, c, h, w = features.size()
      features = features.squeeze(2)
      features = features.permute(0, 2, 1)   # (batch, 32, 256)

    # BiLSTM
      lstm_out, _ = self.rnn(features)        # (batch, 32, 512)

    # Attention with residual connection
      context, attn_weights = self.attention(lstm_out)  # (batch, 32, 512)
      context = context + lstm_out            # RESIDUAL — add original back

    # FC
      output = self.fc(context)               # (batch, 32, num_classes)
      output = output.permute(1, 0, 2)        # CTC format

      return output, attn_weights


# Initialize attention model
attn_model = AttentionCRNN(num_classes=NUM_CLASSES).to(device)
print(f"Attention CRNN parameters: {sum(p.numel() for p in attn_model.parameters()):,}")
print(f"Baseline CRNN parameters:  {sum(p.numel() for p in model.parameters()):,}")

scaler_attn = torch.cuda.amp.GradScaler()
optimizer_attn = torch.optim.Adam(attn_model.parameters(), lr=0.0003)
scheduler_attn = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer_attn, mode='min', factor=0.5, patience=3)

def train_one_epoch_attn(model, loader, optimizer, criterion, device):
    model.train()
    running_loss = 0.0
    for images, labels, label_strs in loader:
        images = images.to(device, non_blocking=True)
        targets, target_lengths = encode_labels(label_strs)
        targets = targets.to(device, non_blocking=True)
        target_lengths = target_lengths.to(device, non_blocking=True)
        optimizer.zero_grad()
        with torch.amp.autocast('cuda'):
            outputs, _ = model(images)          # unpack attention weights
            log_probs = outputs.log_softmax(2)
            input_lengths = torch.full(
                (images.size(0),), outputs.size(0),
                dtype=torch.long, device=device
            )
            loss = criterion(log_probs, targets, input_lengths, target_lengths)
        scaler_attn.scale(loss).backward()
        scaler_attn.step(optimizer_attn)
        scaler_attn.update()
        running_loss += loss.item()
    return running_loss / len(loader)


def validate_attn(model, loader, criterion, device):
    model.eval()
    total_loss = 0
    all_preds, all_targets = [], []
    with torch.no_grad():
        for imgs, labels, label_strs in loader:
            imgs = imgs.to(device, non_blocking=True)
            with torch.amp.autocast('cuda'):
                outputs, _ = model(imgs)        # unpack attention weights
                targets, target_lengths = encode_labels(label_strs)
                targets = targets.to(device, non_blocking=True)
                target_lengths = target_lengths.to(device, non_blocking=True)
                input_lengths = torch.full(
                    (imgs.size(0),), outputs.size(0),
                    dtype=torch.long, device=device
                )
                log_probs = outputs.log_softmax(2)
                loss = criterion(log_probs, targets, input_lengths, target_lengths)
            total_loss += loss.item()
            all_preds.extend(decode_predictions(outputs))
            all_targets.extend(label_strs)
    cer = compute_cer(all_preds, all_targets)
    return total_loss / len(loader), cer, all_preds[:5], all_targets[:5]

NUM_EPOCHS = 30
best_attn_cer = float('inf')
attn_history = {"train_loss": [], "val_loss": [], "val_cer": []}

for epoch in range(NUM_EPOCHS):
    print(f"\nEpoch {epoch+1}/{NUM_EPOCHS}")
    print("-" * 40)

    train_loss = train_one_epoch_attn(
        attn_model, train_loader, optimizer_attn, criterion, device
    )
    val_loss, val_cer, sample_preds, sample_targets = validate_attn(
        attn_model, val_loader, criterion, device
    )
    scheduler_attn.step(val_loss)

    attn_history["train_loss"].append(train_loss)
    attn_history["val_loss"].append(val_loss)
    attn_history["val_cer"].append(val_cer)

    print(f"Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val CER: {val_cer:.4f}")
    print(f"Predictions: {sample_preds}")
    print(f"Targets:     {sample_targets}")

    if val_cer < best_attn_cer:
        best_attn_cer = val_cer
        torch.save(
            attn_model.state_dict(),
            "/content/drive/MyDrive/best_attn_model.pth"
        )
        print(f"  ✓ Saved best attention model (CER: {best_attn_cer:.4f})")

print(f"\nBaseline CER:  {best_cer:.4f}")
print(f"Attention CER: {best_attn_cer:.4f}")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Loss comparison
axes[0].plot(history['val_loss'], label='Baseline Val Loss', linestyle='--')
axes[0].plot(attn_history['val_loss'], label='Attention Val Loss')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].set_title('Validation Loss — Baseline vs Attention')
axes[0].legend()

# CER comparison
axes[1].plot(history['val_cer'], label='Baseline CER', linestyle='--')
axes[1].plot(attn_history['val_cer'], label='Attention CER')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('CER')
axes[1].set_title('Validation CER — Baseline vs Attention')
axes[1].legend()

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/model_comparison.png", dpi=150)
plt.show()

# Show attention weights on a few samples
attn_model.eval()
sample_imgs, _, sample_labels = next(iter(val_loader))
sample_imgs = sample_imgs[:4].to(device)

with torch.no_grad():
    with torch.amp.autocast('cuda'):
        outputs, attn_weights = attn_model(sample_imgs)

preds = decode_predictions(outputs)
attn_weights = attn_weights.squeeze(-1).cpu().numpy()  # (batch, 32)

fig, axes = plt.subplots(4, 2, figsize=(14, 10))
fig.suptitle("Attention Weights — what the model focuses on", fontsize=13)

for i in range(4):
    # Image
    axes[i][0].imshow(sample_imgs[i].cpu().squeeze(), cmap='gray')
    axes[i][0].set_title(f"True: {sample_labels[i]} | Pred: {preds[i]}", fontsize=10)
    axes[i][0].axis('off')

    # Attention weights
    axes[i][1].bar(range(32), attn_weights[i])
    axes[i][1].set_xlabel('Time step (left → right across image)')
    axes[i][1].set_ylabel('Attention weight')
    axes[i][1].set_title('Where the model looks')

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/attention_visualization.png", dpi=150)
plt.show()

"""## Results

| Model | Val CER | Convergence Epoch | Character Accuracy |
|-------|---------|-------------------|-------------------|
| Baseline CRNN | 0.0208 | 29 | 97.9% |
| Attention CRNN | **0.0138** | **26** | **98.6%** |

Attention improved CER by **33.7%** over the baseline.  
The attention model also converged 3 epochs faster.
"""

# Load best model
model.load_state_dict(torch.load("/content/drive/MyDrive/best_model.pth"))
model.eval()

# Test dataset class (no labels)
class TestDataset(Dataset):
    def __init__(self, img_dir):
        self.img_dir = Path(img_dir)
        self.images = sorted(self.img_dir.glob("*.png"))

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = self.images[idx]
        img = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (128, 32))
        img = np.expand_dims(img, axis=0).astype(np.float32) / 255.0
        return torch.tensor(img), img_path.name

test_dataset = TestDataset(TEST_IMG_DIR)
test_loader  = DataLoader(test_dataset, batch_size=64, shuffle=False, num_workers=2)

# Generate predictions
all_filenames = []
all_predictions = []

with torch.no_grad():
    for imgs, filenames in test_loader:
        imgs = imgs.to(device)
        with torch.amp.autocast('cuda'):
            outputs = model(imgs)
        preds = decode_predictions(outputs)
        all_filenames.extend(filenames)
        all_predictions.extend(preds)

# Load best attention model
attn_model.load_state_dict(torch.load("/content/drive/MyDrive/best_attn_model.pth"))
attn_model.eval()

all_filenames, all_predictions = [], []

with torch.no_grad():
    for imgs, filenames in test_loader:
        imgs = imgs.to(device)
        with torch.amp.autocast('cuda'):
            outputs, _ = attn_model(imgs)
        all_filenames.extend(filenames)
        all_predictions.extend(decode_predictions(outputs))

submission = pd.DataFrame({
    'image': all_filenames,
    'prediction': all_predictions
})
submission.to_csv("/content/drive/MyDrive/submission2_AbinayaR_24118002.csv", index=False)
print(f"Saved {len(submission)} predictions")
print(submission.head())

"""## Conclusion

### What we built
A two-stage deep learning pipeline for distorted sequence recognition:
1. **Baseline CRNN** — CNN feature extraction + BiLSTM sequence modeling
   + CTC decoding. Established a strong foundation at CER 0.0208.
2. **Attention CRNN** — Added residual attention on top of the BiLSTM,
   allowing the model to learn which time steps carry the most character
   information. Achieved CER **0.0138** — a 33.7% improvement.

### What the attention visualization confirmed
The attention weight plots show the model consistently focuses on
time steps 1-3 (left edge) and 25-31 (right edge) — exactly where
characters appear unoccluded by the central blob. The model learned,
without being explicitly told, to ignore the occluded center and read
from the visible edges. This is the hypothesis from the error analysis
confirmed empirically.

### What would improve it further
- **Beam search decoding** — replace greedy CTC decode with beam search
  for better sequence-level predictions, typically 1-2% CER improvement
- **Pretrained backbone** — replace the custom CNN with ResNet18;
  richer low-level features from ImageNet pretraining
- **Targeted augmentation** — synthetic blob occlusion and noise during
  training to make the model more robust to unseen distortion patterns
- **Multi-head attention** — richer focus patterns across multiple
  attention heads simultaneously

### Key takeaway
The improvement from baseline to attention was not accidental — it was
driven by a specific hypothesis formed from error analysis, implemented
deliberately, and confirmed by visualizing what the model learned to
focus on. That process — observe, hypothesize, implement, verify — is
what separates engineering from guessing.
"""